config/routes.rb
Rails.application.routes.draw do

  require 'api_constraints'
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1,default: true) do
      get 'galleries/all' => 'galleries#showGalleries'
      resources :galleries
      get 'browse/:id' => 'galleries#browse'
      get 'like/:id' => 'galleries#getLikesSize'
      get 'dislike/:id' => 'galleries#getDislikesSize'
      resources :galleries do
        member do
          put "upvote",to:"galleries#upvote"
          put "downvote",to:"galleries#downvote"
        end
      end
      get 'comments/getRootComments/:id' => 'comments#getRootComments'
      get 'comments/getChildComments/:id' => 'comments#getChildComments'
      post 'comments/setComments/:id' => 'comments#setComments'
      delete 'comments/deleteComments/:id' => 'comments#destroy'
      get 'arts' => 'arts#index'
      get 'arts/:id' => 'arts#show'
      get 'thumb/:id' => 'arts#getThumbUrl'
      get 'allocations' => 'allocations#index'
      get 'allocations/:id' => 'allocations#show'
      post 'getUserName' => 'arts#getUserName'
      post 'getUserEmail' => 'arts#getUserEmail'

    end
  end
  root 'galleries#index'
      patch 'allocations/:id' => 'allocations#update'
  resources :galleries,:path =>"/sammlung"
  get 'browse/:id' => 'galleries#browse'
  get 'like/:id' => 'galleries#getLikesSize'
  get 'dislike/:id' => 'galleries#getDislikesSize'
  get 'galleries/all',to:"galleries#showGalleries"
  get 'maps',to: "galleries#maps"

  get 'tags/:tag', to: 'galleries#index', as: :tag

  get 'static_pages/datenschutz'
  get 'static_pages/impressum'
  get 'static_pages/nutzungsbedingungen'
  get 'static_pages/publishPicture/:id',to: 'static_pages#publishPicture'
  
  resources :galleries do
    member do
      put "upvote",to:"galleries#upvote"
      put "downvote",to:"galleries#downvote"
    end
  end

  resources "contact_mails", only: [:new, :create]
  resources "comment_mails", only: [:new, :create]
  resources :privacies
  resources :impressums

  resources :arts,:path =>"/bilder"
  

  resources :users
  devise_for :users, controllers: {
       sessions: 'users/sessions',
       registrations: 'users/registrations'
  },:path_prefix => 'my'

  as :user do
    get "/login" => "users/sessions#new"
    get "/logout" => "users/sessions#destroy"
  end

  resources :impressums do
    member do
      put "upi", to: "impressums#upi"
      put "downi", to: "impressums#downi"
    end
  end
  resources :privacies do
    member do
      put "upspr", to: "privacies#upspr"
      put "downspr", to: "privacies#downspr"
    end
  end
  delete 'comments' => 'comments#destroy'
  get 'comments/index' => 'comments#index'
  resources :comments do

    member do
      get "getComments", to: "comments#getComments"
      post "setComments", to: "comments#setComments"
    end
  end

end

app/models/impressum.rb
class Impressum < Position
end

app/controllers/impressums_controller.rb
class ImpressumsController < ApplicationController
  before_action :set_impressum, only: [:update, :destroy]
  load_and_authorize_resource
  skip_authorize_resource :only => [:index]

  #function to chance the position of a triviapage 1 up
  def upi
    Impressum.find(params[:id]).up

    @impressums = Impressum.order(position: :asc)
    redirect_to :back
  end

  #function to chance the position of a triviapage 1 down
  def downi
    Impressum.find(params[:id]).down

    @impressums = Impressum.order(position: :asc)
    redirect_to :back
  end

  # GET /impressums
  # GET /impressums.json
  def index
    @impressums = Impressum.order(position: :asc)
  end

  # GET /impressums/1
  # GET /impressums/1.json
  def show
    redirect_to impressums_url
  end

  # GET /impressums/new
  def new
   @impressum = Impressum.new
    respond_to do |format|
     format.html{redirect_to impressums_url}
     format.js {}
    end
  end
  # GET /impressums/1/edit
  def edit
     respond_to do |format|
      format.html{redirect_to impressums_url}
      format.js {}
    end
  end

  # POST /impressums
  # POST /impressums.json
  def create
    @impressum = Impressum.new(impressum_params)
    @impressum.position=Impressum.all.count+1
    respond_to do |format|
      if @impressum.save
        format.html { redirect_to impressums_url, notice: I18n.t('ecreate') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /impressums/1
  # PATCH/PUT /impressums/1.json
  def update
    respond_to do |format|
      if @impressum.update(impressum_params)
        format.html { redirect_to impressums_url, notice: I18n.t('eupdated') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /impressums/1
  # DELETE /impressums/1.json
  def destroy
    @impressum.destroy
    rebuild Impressum
    respond_to do |format|
      format.html { redirect_to impressums_url, notice: I18n.t('edestroy') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_impressum
      @impressum = Impressum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def impressum_params
      params.require(:impressum).permit(:text, :position)
    end
end

app/helpers/impressums_helper.rb
module ImpressumsHelper
end

app/views/impressums/_edit.html.erb
<%= render 'form' %>
<%= link_to I18n.t('back'), impressums_path,:class=>"btn btn-primary" %>

app/views/impressums/_form.html.erb
<%= render "static_pages/editor"%>
<%= form_for(@impressum) do |f| %>
<% if @impressum.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@impressum.errors.count, "error") %> gefunden die das Abspeichern verhindern:</h2>

	<ul>
		<% @impressum.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :text %>
	<br>
	<%= f.text_area(:text, size: '50x10',:class => "editor") %>
</div>
<div class="actions">
	<%= f.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/impressums/edit.js.erb
$('#<%= @impressum.position %>').html("<%= j (render 'edit') %>");

app/views/impressums/index.html.erb
<div class="container">
	<div class="row">
		<% @impressums.each do |impressum| %>
			<div class="well" id="<%= impressum.position%>">
				<% if can? :edit, @impressums %>
					<%= link_to "", upi_impressum_path(impressum), method: :put,:class=>"glyphicon glyphicon-arrow-up"%>
					<%= link_to "", downi_impressum_path(impressum), method: :put,:class=>"glyphicon glyphicon-arrow-down" %>
				<%end %>
				<%= raw(impressum.text)%>
				<% if can? :edit, @impressums %>
					<%= link_to I18n.t('edit'), edit_impressum_path(impressum),remote: true,:class=>"btn btn-primary" %>
					<%= link_to I18n.t('destroy'), impressum, method: :delete, data: { confirm: 'Sind Sie sicher?' },:class=>"btn btn-primary" %>
				<%end%>
			</div>
		<%end%>
		<div id="new">
		</div>
	</div>
	<% if can? :edit, @impressums %>
		<%= link_to I18n.t('neuereintrag'), new_impressum_path,remote: true,:class=>"btn btn-primary" %>
	<%end%>
</div>

app/views/impressums/new.js.erb
$('#new').html("<%= j (render 'edit') %>");